### ISSUE TITLE
GIS File issue

### ISSUE THREAD

**Issue by dedsresende** [atolcd/pentaho-gis-plugins#13]
I've been trying to use the GIS plugin for pentaho but no matter which file I try to run by the GIS File input when I plug it into any other brick (Geoprocessing, Spatial relationships and so on) I got the following issue:

Unable to open dialog for this step
java.lang.NoClassDefFoundError: org/apache/commons/vfs/FileSystemException
	at com.atolcd.pentaho.di.trans.steps.gisfileinput.GisFileInputMeta.getFields(GisFileInputMeta.java:211)
	at org.pentaho.di.trans.TransMeta.compatibleGetStepFields(TransMeta.java:2057)
	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2043)
	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1874)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1943)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1908)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1894)
	at com.atolcd.pentaho.di.ui.trans.steps.gisrelate.GisRelateDialog.getFieldsFromType(GisRelateDialog.java:649)
	at com.atolcd.pentaho.di.ui.trans.steps.gisrelate.GisRelateDialog.open(GisRelateDialog.java:418)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:127)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8789)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3179)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:775)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1359)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7990)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9290)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:685)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs.FileSystemException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:89)
	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:108)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more

How can this be solved?

Best,

**Comment by 300000kms** [comment]
+1, also the same issue!

**Comment by roboguy** [comment]
@dedsresende , @300000kms - are you trying to run on PDI 6+ ? If yes, PDI moved to using VFS2. This library still uses VFS1. There is a pull request that you can use to change vfs to vfs2. Its a simple change of imports to org.apache.vfs2

**Comment by cvagner** [comment]
Hi,
It must be fixed. Please, can you retry with the last version and let you comments here ?

**Comment by dwadmin49** [comment]
Hi,

Sorry but I have the same problem today : 

> ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : Unexpected error
ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : java.lang.NoClassDefFoundError: org/apache/commons/vfs/FileSystemException
at com.atolcd.pentaho.di.trans.steps.gisfileoutput.GisFileOutput.processRow(GisFileOutput.java:73)
at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs.FileSystemException
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:89)
at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:108)
at java.lang.ClassLoader.loadClass(Unknown Source)


Kettle version : pdi-ce-8.0.0.0-28 (latest)
Plugin source : marketplace
