### ISSUE TITLE
Format date attendue par le plugin

### ISSUE THREAD

**Issue by TERMEPhilippe** [atolcd/pentaho-gis-plugins#34]
Lors de l'extraction d'une table Geopackage, PDI me retourne cette erreur sur un champ date : 
Error reading features :Unparseable date: "Thu Aug 31 02:00:00 CEST 2023"
2024/05/02 11:41:14 - Extraction depuis fichier SIG.0 - 
2024/05/02 11:41:14 - Extraction depuis fichier SIG.0 - 	at com.atolcd.pentaho.di.gis.io.GeoPackageReader.getFeatures(GeoPackageReader.java:329)
2024/05/02 11:41:14 - Extraction depuis fichier SIG.0 - 	at com.atolcd.pentaho.di.trans.steps.gisfileinput.GisFileInput.processRow(GisFileInput.java:126)
2024/05/02 11:41:14 - Extraction depuis fichier SIG.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2024/05/02 11:41:14 - Extraction depuis fichier SIG.0 - 	at java.lang.Thread.run(Unknown Source)

 J'ai tenté tous les formats mais l'erreur est invariable. Quel format date doit-on fournir dans me gpkg pour qu'il soit pris en compte par le plugin ? 
Merci

**Comment by cvagner** [comment]
Bonjour,

Il semblerait que le format attendu soit **YYYY-MM-DD** pour une date, visible [ici](https://github.com/atolcd/pentaho-gis-plugins/blob/0790087705ca9539b3042a878ebba8acb5c98063/pentaho-gis-plugins/src/main/java/com/atolcd/pentaho/di/gis/io/GeoPackageReader.java#L63).

Pouvez-vous tester SVP ?

**Comment by TERMEPhilippe** [comment]
bonjour, et merci pour le retour rapide, hélas non concluant. Mais les conventions d'écriture ne devraient-elles pas être yyyy-MM-dd ?

**Comment by cvagner** [comment]
Oui, vous avez raison. J'ai répondu rapidement pour fournir un pointeur mais sans analyser car je n'ai pas de temps alloué actuellement.
* https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html

Je vois également qu'il y a une coquille à la ligne du dessous pour le date time (un espace en début de format).

Avez-vous moyen de compiler une version ?
Le [README](https://github.com/atolcd/pentaho-gis-plugins/blob/master/pentaho-gis-plugins/README.md) décrit la procédure.
